# Generated by Django 5.2.11 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department_roll_code_batch'),
        ('attendance', '0003_attendance_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='academics.batch'),
        ),
    ]
