# Generated by Django 5.2.11 on 2026-04-08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='roll_code',
            field=models.CharField(
                blank=True,
                help_text='Two-digit department code used in roll numbers, e.g., 03',
                max_length=2,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Roll code must be exactly 2 digits.')],
            ),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Intake year, e.g., 2026')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'department',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.department'),
                ),
            ],
            options={
                'ordering': ['department', '-year'],
                'unique_together': {('department', 'year')},
            },
        ),
    ]
