# Generated by Django 5.2.11 on 2026-04-08

import django.core.validators
from django.db import migrations, models


def backfill_batch_codes(apps, schema_editor):
    Batch = apps.get_model('academics', 'Batch')
    for batch in Batch.objects.all():
        if not batch.code and batch.year:
            batch.code = str(batch.year)[-2:]
            batch.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department_roll_code_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='code',
            field=models.CharField(
                blank=True,
                help_text='Two-digit batch code used in roll numbers, e.g., 26 or 78',
                max_length=2,
                null=True,
                validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Batch code must be exactly 2 digits.')],
            ),
        ),
        migrations.RunPython(backfill_batch_codes, migrations.RunPython.noop),
    ]
