# Generated by Django 5.2.11 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_batch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='locked_semester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Current locked semester for this batch (1-8).', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='semester_lock_enabled',
            field=models.BooleanField(default=True, help_text='When enabled, students in this batch are restricted to one locked semester.'),
        ),
    ]
