# Generated by Django 5.2.11 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department_roll_code_batch'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Student intake batch/cohort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='batch_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='Sequence number within selected batch and department', null=True),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('batch', 'batch_sequence'), name='unique_batch_student_sequence'),
        ),
    ]
